[project]
name = "eye"
version = "1.1.0"
description = "Eye of the Swarm"
readme = "README.md"
requires-python = ">=3.12,<3.13"
authors = [{ name = "Tomas Votava", email = "info@tomasvotava.eu" }]
dependencies = [
    "platformdirs>=4.11.5",
    "pygame-ce>=2.5.8",
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
  "mypy>=2.3.1",
  "pre-commit>=4.6.2",
  "pygbag>=0.9.3",
  "pyinstaller>=6.22.3",
  "pytest>=9.1.1",
  "ruff>=0.16.5",
  "typing-extensions>=4.16.0",
]

[tool.mypy]
strict = true
python_version = "3.12"

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = [
  "E",
  "F",
  "B",
  "I",
  "N",
  "UP",
  "S",
  "A",
  "DTZ",
  "PT",
  "SIM",
  "PTH",
  "PD",
  "RUF",
  "T20"
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "RUF018", "S311"]
