from typing import Protocol

import pygame


class Scene(Protocol):
    def handle_pygame_event(self, pygame_event: pygame.event.Event) -> None: ...
    def update(self, dt: float) -> Scene | None: ...
    def draw(self, surface: pygame.Surface) -> None: ...
