"""Every magic number in the exploration engine — encounter-kind weights and resource pickup
magnitudes. Values are playtesting-driven placeholders (PROJECT_BRIEF.md §8), not final tuning.
"""

ENCOUNTER_KIND_WEIGHT_ENEMY = 1.0
ENCOUNTER_KIND_WEIGHT_EFFECT_PICKUP = 1.0
ENCOUNTER_KIND_WEIGHT_RESOURCE_PICKUP = 1.0
ENCOUNTER_KIND_WEIGHT_NOTHING = 1.0

RESOURCE_HEAL_MAGNITUDE = 10
RESOURCE_SPORES_MAGNITUDE = 5
RESOURCE_SEED_GROWTH_MAGNITUDE = 10
RESOURCE_DISTANCE_DISCOUNT_MAGNITUDE = 1

SEED_GROWTH_THRESHOLD = 100.0
SEED_GROWTH_BASE_RATE = 5.0
SEED_GROWTH_DISTANCE_FACTOR = 2.0
SEED_GROWTH_RATE_CAP = 25.0


def seed_growth_rate(distance: float) -> float:
    return min(SEED_GROWTH_RATE_CAP, SEED_GROWTH_BASE_RATE + SEED_GROWTH_DISTANCE_FACTOR * distance)
